{"name": "test_validate_csv[C:\\Users\\vybor\\PycharmProjects\\Yadro\\csv\\test_broken.csv]", "status": "passed", "description": "Checking csv_files_invalid", "parameters": [{"name": "path_invalid", "value": "'C:\\Users\\vybor\\PycharmProjects\\Yadro\\csv\\test_broken.csv'"}], "start": 1675003855641, "stop": 1675003855642, "uuid": "3ff5a5bf-8c00-4fd0-8c80-18cc8194a99f", "historyId": "2581eb7b9a2871f71a995713ee18d953", "testCaseId": "6d42316c1b8fbf2f0a4906cb3ebfc5fc", "fullName": "tests.test_validate_csv.TestCSV#test_validate_csv", "labels": [{"name": "story", "value": "A correct error was received with invalid values in csv"}, {"name": "epic", "value": "Test create place"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_validate_csv"}, {"name": "subSuite", "value": "TestCSV"}, {"name": "host", "value": "DESKTOP-19E6A29"}, {"name": "thread", "value": "5412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_validate_csv"}]}