{"name": "test_validate_csv[C:\\Users\\vybor\\PycharmProjects\\Yadro\\csv\\test_broken_headers.csv]", "status": "passed", "description": "Checking csv_files_invalid", "parameters": [{"name": "path_invalid", "value": "'C:\\Users\\vybor\\PycharmProjects\\Yadro\\csv\\test_broken_headers.csv'"}], "start": 1675003855645, "stop": 1675003855646, "uuid": "d1a2152f-8eba-419c-be31-235534c72280", "historyId": "386170af0fe87010ec09138c9a3291f1", "testCaseId": "6d42316c1b8fbf2f0a4906cb3ebfc5fc", "fullName": "tests.test_validate_csv.TestCSV#test_validate_csv", "labels": [{"name": "story", "value": "A correct error was received with invalid values in csv"}, {"name": "epic", "value": "Test create place"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_validate_csv"}, {"name": "subSuite", "value": "TestCSV"}, {"name": "host", "value": "DESKTOP-19E6A29"}, {"name": "thread", "value": "5412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_validate_csv"}]}